### PR TITLE
Test lazy loaded images filtering. Run tests in CI.

### PR DESCRIPTION
**Pull request by govza**
#### Changes
e2e tests DDG search results
refactor single image tests
tests run sequentially  (otherwise there tons of performace issues).
CI tests enabled (takes time)

jest-puppeteer

Fixes # (issue)
tests

#### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by YegorZaremba** [comment]
Man, you are the beast :rocket: 
Will check later

**Comment by govza** [comment]
I don't know why, but there strong regression on singleNSFW and some of the criteria, so it is disabled. 
Also should be mentioned that tests are using default settings, since interaction from puppeteer to extension is really complicated.
I'll check how it works on previous model or maybe it is new strictness level impact, idk.

**Comment by YegorZaremba** [comment]
Sorry man, it was a bug, dunno why I put it here, fixed https://github.com/nsfw-filter/nsfw-filter/pull/115

**Comment by YegorZaremba** [comment]
```
FAIL test/e2e/singleNSFW.test.js (14.51 s)
  Should filter NSFW images
    ✕ Check single NSFW image https://i.imgur.com/0XUW69F.jpg (3084 ms)
    ✓ Check single NSFW image https://i.imgur.com/0ZW7Cyo.jpg (3085 ms)
    ✓ Check single NSFW image https://i.imgur.com/0avXzJF.jpg (3053 ms)
```

hmm test works, maybe just increase time of model loading? 
`await page.waitForTimeout(5000)` to 8000 or 10000

**Comment by govza** [comment]
@YegorZaremba maybe we can discuss in slack? I believe we have regression with new model. I made a test pr with same tests on old model.

**Review by YegorZaremba — APPROVED** [review]
@govza Great work, especially thanks for adding ability to run tests in CI :rocket:

**Pull request merged**
