### PR TITLE
Feat/add Grayscale filter effect

### LINKED ISSUE #229: Grayscale filter effect
#### Is your feature request related to a problem? Please describe.

In addition to Hide and Blur filter effect, I believe Grayscale one will work for our mental hygiene.

#### Describe the solution you'd like

Adding "Grayscale" option for "Filter effect" select box in popup is enough.

#### Describe alternatives you've considered

It may be powerful that Blur filter effect also makes NSFW images grayscale.

#### Additional context

Let's check up how it works: https://www.google.com/search?q=sexy&tbm=isch&tbs=ic:gray

### PR DESCRIPTION
**Pull request by silloi**
#### Changes
 

- Grayscale filter is added for the style to show images
- Grayscale option is added to Filter effect select box
- `grayscale` lateral type is added for `filterEffect`

resolve #229

[Image from Gyazo](https://gyazo.com/420c4961381f6e067105c8617590f327)
[Image from Gyazo](https://gyazo.com/a24371ee11488ce4757f6ecf99a948c0)

#### Type of change

- [x] New feature (non-breaking change which adds functionality)

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by yzevm — APPROVED** [review]

**Comment by yzevm** [comment]
@silloi great work :heart_eyes:

**Comment by navendu-pottekkat** [comment]
@silloi @yzevm Tried creating a new release and updating the version in the webstore with this feature added but the CI release jobs seems to be failing. Any ideas?

https://github.com/nsfw-filter/nsfw-filter/actions/runs/4517161269/jobs/7956157451#step:4:53

**Comment by silloi** [comment]
@navendu-pottekkat This error seems to be resulted from Node.js, which used to be v16.19.1 as a default of GitHub Actions, but now v18.15.0.
On the other hand, integration workflow uses `@actions/node-setup` to fix node version to 16.x. So I do the same to release one in #237. I believe this fix makes it succeed.

Basically, this error seems to be derived from webpack v4, which is deprecated to node < v17. (See https://github.com/webpack/webpack/issues/14532)
I tried upgrading it, but not working so far 😓
Besides, if we use node v18 when release workflow, we might do the same on integrate workflow too.

**Comment by navendu-pottekkat** [comment]
@silloi Thank you for checking this out. Let me merge the PR and check.

**Comment by navendu-pottekkat** [comment]
Here is the new run of the workflow: https://github.com/nsfw-filter/nsfw-filter/actions/runs/4517161269/jobs/7957443905

**Comment by navendu-pottekkat** [comment]
@all-contributors please add @silloi for ideas, bugs, and code

**Pull request merged**
