### PR TITLE
fix: redundant permissions

### PR DESCRIPTION
**Pull request by YegorZaremba**
Fixed: #31

### CODE REVIEW

**Comment by YegorZaremba** [comment]
Im still confused with `activeTab` and `<all_urls>`. If you `open link in new tab` and stay on your current tab, our extension will filter images in the new tab too, and thats awesome. But for permission policy better use `activeTab` Im not sure do we have access to `DOMContentLoaded` event for `open link in new tab` pages in that case, anyway lets try this bunch of permissions first

**Comment by YegorZaremba** [comment]
You cannot test it with `dev` mode(god mode), best solution is upload on chrome websore and check every permission over there

**Comment by navendu-pottekkat** [comment]
> You cannot test it with `dev` mode(god mode), best solution is upload on chrome websore and check every permission over there

The problem is Chrome takes it very seriously and they take a lot of time to verify permissions and approve it. I have already submitted a version. Let's see how it does. and then lets update the version.

**Comment by navendu-pottekkat** [comment]
If Chrome rejects the current version we will put up the updated version. Once we have it on the Chrome webstore more people will start using it.

**Comment by navendu-pottekkat** [comment]
> Looks good to me

@ClayMav @YegorZaremba We will check if the current version gets in the store. If not, we will build one from this branch and see. If everything works after deployment, we will merge it. What say?

**Comment by navendu-pottekkat** [comment]
@all-contributors please add @ClayMav for review

**Comment by ClayMav** [comment]
Sounds like a plan. Shame there isn't a better way to test the permissions locally.

**Pull request closed without merging**
