### PR TITLE
v1.2.0

### PR DESCRIPTION
**Pull request by YegorZaremba**
#### Changes
Extension

- [x] Feat: add prediction queue to avoid duplication
- [x] Feat: add analyzer for GIF images 
- [x] Feat: add analyzer for video (only if video contains poster URL)
- [x] Fix: analyze only valid links from dataset attribute
- [x] Fix: remove observation of attributes mutation (except `src`)

Codebase

- [x] Refactor: move to TypeScript and Webpack
- [x] Refactor: classes and methods decomposition

#### Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by YegorZaremba** [comment]
Hi @navendu-pottekkat I finished, it works for firefox and chrome, just pull, test and accept PR. After that, I'll merge it

**Review by navendu-pottekkat — APPROVED** [review]
Looks good while testing. 

Lots of changes!

The 128x128 icon image is the one without the background removed, so we should change that. 

Maybe bump the version in the package.json file. 

I think with the changes we can merge and make releases in Webstore and Mozilla Addons.

**Comment by YegorZaremba** [comment]
Could you please send me 128x128 image cause I cannot find that size in archive which you sent

**Comment by navendu-pottekkat** [comment]
> Could you please send me 128x128 image cause I cannot find that size in archive which you sent

@YegorZaremba I shared it now on slack

**Comment by YegorZaremba** [comment]
Done, lets release v1.2.0 :rocket:

**Pull request merged**
