### PR TITLE
Use web-ext to run extension for development.

### LINKED ISSUE #107: npm run test fails on windows
#### Bug description
npm run test fails on windows

#### Expected result
tests are run

#### Actual result
HEADLESS=false jest --no-cache
'HEADLESS' is not recognized as an internal or external command,

#### Steps to reproduce
1. npm ci
2. npm run build
3. npm run test

#### Context
Windows doesn'nt recognizes the environment setup

#### Your Environment
Windows 10 pro, node v14.6.0

### PR DESCRIPTION
**Pull request by govza**
#### Changes
Ease to start development in clean environment with one command.
i.e. ```npm run dev:chrome``` 
Fixes windows developers experience.

devDependencies:
web-ext
cross-env
npm-run-all

Fixes #107

#### Type of change

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] This change requires a documentation update

#### Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by navendu-pottekkat** [comment]
@govza Thank you for your contribution, we will test out the PR and get back to you.

**Comment by YegorZaremba** [comment]
Hi @govza looks great, really good one, will check tomorrow

**Comment by YegorZaremba** [comment]
Hi @govza, I checked - LGTM, could you please resolve conflicts, after that I will merge it
thanks for contributing

**Comment by govza** [comment]
@YegorZaremba rebased

**Review by YegorZaremba — APPROVED** [review]

**Comment by YegorZaremba** [comment]
@all-contributors please add @hsusanoo for bug, code

**Comment by YegorZaremba** [comment]
@all-contributors please add @govza for bug, code

**Pull request merged**
