### PR TITLE
Remove redundant puppeter jest preset dependecy

### PR DESCRIPTION
**Pull request by govza**
#### Changes
More stable tests. Basically we don't test prediction accuracy here but the work of the mutation observer
Removed jest-puppeteer as abandoned and generally redundant
Removed npm warnings considering deprecated packages and formatting of some of the fields.

Fixes # 
warnings, tests

#### Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

#### Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by YegorZaremba** [comment]
@govza dunno but looks like I broke current version in `master` yesterday

**Comment by govza** [comment]
@YegorZaremba Its still flaky, I'll rebase after your merge and try to fix it.

**Comment by govza** [comment]
@YegorZaremba Ready for review.
I believe the tests were flaky because of global page usage with puppeteer.

**Comment by YegorZaremba** [comment]
@govza Great work, I'll `git pull` and check it locally in the next 48 hrs :+1:

**Review by yezz123 — COMMENTED** [review]
this changes and edits are soo helpful 
Nice catch !

**Comment by YegorZaremba** [comment]
Hi @govza  work is really awesome, but I re-run tests to check stability of them and `hentai` test is fallen
```
   ● Should filter NSFW lazy loaded images › search for Hentai should block at least one of the NSFW images

    : Timeout - Async callback was not invoked within the 100000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 100000 ms timeout specified by jest.setTimeout.Error:
```
Do you have any clue on this mystery?

**Comment by YegorZaremba** [comment]
@govza I hope it's enough for now :smile: #132 

```
console.log
blocked 1 from 4 duckduckgo search results of Hentai

  at e2e/mutationNSFW.test.js:31:17

console.log
blocked 2 from 2 duckduckgo search results of Sexy

  at e2e/mutationNSFW.test.js:31:17

console.log
blocked 7 from 8 duckduckgo search results of Porn

  at e2e/mutationNSFW.test.js:31:17

PASS test/e2e/mutationNSFW.test.js (134.953 s)
Should filter NSFW lazy loaded images
✓ search for Hentai should block at least one of the NSFW images (33322 ms)
✓ search for Sexy should block at least one of the NSFW images (32803 ms)
✓ search for Porn should block at least one of the NSFW images (32713 ms)
✓ search for Nature should show at least one of the SFW images (32812 ms)

console.log
blocked 0 from 2 duckduckgo search results of Nature
```

**Pull request merged**
