### PR TITLE
Fix mutation observer, search for img nodes recursively in mutated no…

### LINKED ISSUE #60: failed to hide images
#### Bug description

failed to hide all nsfw images

#### Expected result

all nsfw images should be hidden

#### Actual result

some nsfw images were not hidden

#### Steps to reproduce

1. go to bing.com
2. search for "nsfw"
3. click images
4. turn off safe search
5. scroll down to find images that were not properly hidden by the extension

#### Context

i like the idea of the extension and would like it to be improved

#### Your Environment

* Version used: 1.0
* Browser Name and version: chrome 85
* Operating System and version: windows 10
* Link to your project: n/a

### PR DESCRIPTION
**Pull request by govza**
…delist.

#### Changes
 Fix child nodes of mutated nodes analytics.

Fixes #60 

#### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by YegorZaremba — COMMENTED** [review]
Hi @govza I thought that it's unnecessary cause we have `subtree = true`  param
https://developer.mozilla.org/en-US/docs/Web/API/MutationObserverInit/subtree

Could you please give more info about these changes, better to send a link(test-case) which shows your point

**Comment by YegorZaremba** [comment]
I close this PR, but if I'm wrong - feel free to ping for reopen

**Comment by govza** [comment]
Yes you right. Checked this again, and looks like it's bug only on scrolller .com

**Comment by YegorZaremba** [comment]
no no no :), I went to this website, and yeap its a bug. Looks like they use `img.srcset` instead of `img.src`
Nice catch!

**Comment by YegorZaremba** [comment]
@govza if you have free time could you please test current version in `master`, we would like to release in the next week, but we have lack of testing

**Comment by YegorZaremba** [comment]
Hi @govza thanks a lot for catching this tricky bug, I appreciate it. I tried your solution and found that it checks childNodes for every `div`. For example scroller .com my counter shows 12k+ iterations - we gonna have some perf issues in the future. So I decided to subscribe when new `MutationList` come out and if type of it is `childList`(cause `attributes` is not our case) we will find all images on the page and re-check them, for scroller .com it takes 9 calls. For average webpage it takes ~100 calls. Yeah, not perfect solution, but it works. Here is PR #135

**Pull request closed without merging**
