### PR TITLE
Olostep tipping integration complete

### PR DESCRIPTION
**Pull request by olostep**
- Bumped to version 2.3.1
- Introduced OlostepExt.js library
- Modified the popup's index.tsx to introduce "Support with a Donation"
- Modified webpack.common.js to also copy the OlostepExt.js file in the final dist

#### Changes
I introduced the OlostepExt.js file and modified the popup's index.tsx file to create another span under the "Sponsor on Patreon" portion. The Olostep library gets initialized in the background.ts file. I also imported the Olostep file into the content.ts file to call olostep.tips.request()

#### Type of change
- [x] New feature (non-breaking change which adds functionality)

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by pottekkat** [comment]
@olostep Thank you for opening the PR. It would hopefully help us make the project sustainable. We will add our reviews soon.

**Comment by pottekkat** [comment]
@olostep Tried running it locally but it does not seem to work properly. Could you check?


https://github.com/nsfw-filter/nsfw-filter/assets/49474499/8e2c7b65-9ebc-4f52-bb2a-e5e08e7e6eb1

**Comment by olostep** [comment]
@pottekkat Thanks for the ping. I checked: on the new tab(chrome://new-tab-page/), it does not appear to work properly since there's no content script running. Will introduce a fix (probably a fallback URL) in the library and let you know. Thanks

**Comment by olostep** [comment]
Closing this for now as the project has been momentarily discontinued

**Pull request closed without merging**
