### PR TITLE
docs: update demo gif

### PR DESCRIPTION
**Pull request by YegorZaremba**
Covering more cases
@navendu-pottekkat pls take a look

### CODE REVIEW

**Review by navendu-pottekkat — COMMENTED** [review]
Some of the images that are visible in the demo could be considered as NSFW right, in the demo I made, I could add the results for cats or something of that sorts. Like, complete blocking of one category and completely allow images of another category.

**Comment by navendu-pottekkat** [comment]
@Just so the demo looks cleaner.

**Comment by YegorZaremba** [comment]
> Some of the images that are visible in the demo could be considered as NSFW right, in the demo I made, I could add the results for cats or something of that sorts. Like, complete blocking of one category and completely allow images of another category.

Its fine cause our model has 95% accuracy, just prepare users for that. Im not prefer demo where all result blocked or showed

Okey maybe we need to change `nudes` to sth else, but I believe that we should use `sexy` and `cats` for demo
Also make sure that your recording resolution is squarish and window zoom is 120-130% that users can see search words

**Comment by navendu-pottekkat** [comment]
@YegorZaremba You can record it. But make sure no NSFW images are shown because then we cannot add something like that directly in the readme. The way you suggested works.

**Pull request closed without merging**
