### PR TITLE
Improve Docs

### PR DESCRIPTION
**Pull request by Andrewrick1**

### CODE REVIEW

**Comment by navendu-pottekkat** [comment]
Hey @Andrewrick1 I think what we have currently in the doc is fine. If you are looking to contribute to Hacktoberfest, please check the [open issues](https://github.com/nsfw-filter/nsfw-filter/issues)

**Review by navendu-pottekkat — CHANGES_REQUESTED** [review]
The current version is fine in my opinion

**Comment by YegorZaremba** [comment]
@navendu-pottekkat why did you use upper case? @Andrewrick1's PR is LGTM
Screen Shot 2020-10-01 at 5 35 42 PM

**Review by YegorZaremba — APPROVED** [review]

**Comment by navendu-pottekkat** [comment]
@YegorZaremba I thought it was all caps for some reason? Or does it work better? I do not remember why and why we have not changed it after all these iterations to the README.

There has been a lot of spam PRs in my other repos today. I rejected it because of that. But since the extension page has Load unpacked I think we can approve the PR.

Sorry, @Andrewrick1 My bad!

**Review by navendu-pottekkat — APPROVED** [review]

**Comment by navendu-pottekkat** [comment]
@all-contributors please add @Andrewrick1 for docs

**Pull request merged**
